# Generated by Django 2.0.1 on 2018-02-18 01:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MailEmployeer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('address', models.EmailField(max_length=100)),
                ('type_mail', models.IntegerField(choices=[(1, 'Personal'), (2, 'Professional')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='MailManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('address', models.EmailField(max_length=100)),
                ('type_mail', models.IntegerField(choices=[(1, 'Personal'), (2, 'Professional')], default=1)),
            ],
        ),
    ]
