# Generated by Django 2.0.1 on 2018-05-10 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailemployeer',
            options={'ordering': ('created',)},
        ),
        migrations.AlterModelOptions(
            name='mailmanager',
            options={'ordering': ('created',)},
        ),
    ]
