# Generated by Django 2.0.1 on 2018-01-03 02:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('code', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('url', models.URLField(blank=True, max_length=500)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
